### PR TITLE
docs: dutch translations

### PR DESCRIPTION
**Pull request by ThimoDEV**
reference #540 

As far as I can see I have done all translations for dutch.
Would love to hear feedback 🤗

### CODE REVIEW

**Comment by alvarosabu** [comment]
I think there is no better person to take a look at this than you buddy @kissu 🤗

**Comment by kissu** [comment]
Yo chamo ! 👋🏻 
I do indeed live in Amsterdam but to be honest, I am clearly not interested into learning Dutch. 😌
You could ask me for Russian or French but I am not a great candidate for that one. 🫣

**Review by kissu — APPROVED** [review]
Despite sending it to Deepl I am to no use here. Let's trust OP. 🤗

**Comment by ThimoDEV** [comment]
I'll have a second look this weekend. Then you can merge I think and if theres still mistakes in the docs a new PR can be opened for that.

Great to see all the multi culture here 😁.

**Pull request merged**
