### PR TITLE
feat: 499 better memory management

### LINKED ISSUE #449: Memory leak caused by non disposed scene, when using routes
### Describe the bug

In our project, we use a bit big bigger models and we test our app on mobile browsers. While observing the memory, it became clear that unmounting the TresCanvas, does not properly dispose the scene and some (maybe all) internal objects. So navigating in and out a few times on iOS device, cause the page to crash and reload, because it runs out of memory.

Screenshot 2023-11-19 at 20 15 16

Unfortunately, my understanding of three.js is not much, but I had similar issues in the past and it was related to the way the scene and objects, that were added to the scene, being not properly disposed. Its possible that some references to some internal TresJS objects are also the cause of the issue. I just dont know.

Its also possible that I am missing something in the way I use the framework (which will be the best for me), so hopefully someone can give me a hand with this.

Thank you!

### Reproduction

https://stackblitz.com/edit/tresjs-basic-tmk778

### Steps to reproduce

To reproduce, open the reproduction link in a Chromium browser and use the `Memory` tab in the dev tools. 
At the top of the web page, you will find a basic navigation, that routes into two separate pages, where "The Experience" loads the TresCanvas and "Home" is used to unmount the other one.

### System Info

_No response_

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by alvarosabu**
Hopefully closes #449 

- Recursive removal of nodes dispose (GPU) of all three disposable properties and removes refs (CPU) **if the node is not primitive**
- If it is a primitive, the user needs to handle the disposal manually by using a `dispose` function

Todo

- [x] Docs

### CODE REVIEW

**Comment by andretchen0** [comment]
Sure thing! I'll have a look.

----

## Tests?

I feel like the answer to "Should this be disposed?" is hard to explain. And that means the implementation will be easy to break in the future.

Tests would probably help both in explaining the functionality to maintainers and in ensuring future changes don't accidentally break the functionality.

At first glance, I don't see any tests about resource disposal. Would you like me to add some tests?

**Comment by alvarosabu** [comment]
Before the tests @andretchen0 , I'm struggling to dispose the whole scene on the unmount hook of the TresCanvas when changing a route, the GPU is clear but not the CPU memory allocation 🥲. I will push the latest code I used to try to make it work

**Comment by andretchen0** [comment]
> Before the tests @andretchen0 , I'm struggling to dispose the whole scene on the unmount hook of the TresCanvas when changing a route, the GPU is clear but not the CPU memory allocation 🥲. I will push the latest code I used to try to make it work

Sure thing. 

Can you walk me through the steps you're taking – in the Chrome dev tools? – so that we're looking at the same data?

**Comment by alvarosabu** [comment]
Hi @andretchen0 here is a video with the reproduction steps


https://github.com/Tresjs/tres/assets/4699008/bbb57f9e-6b0f-48fe-90ac-8c0b67ce9641

**Comment by alvarosabu** [comment]
I think I found the reason @andretchen0, the refs kept on the CPU are entirely related to the devtools. This doesn't occur in production build.

**Comment by andretchen0** [comment]
> I think I found the reason @andretchen0, the refs kept on the CPU are entirely related to the devtools. This doesn't occur in production build.

I came here to post this. Lol. 👍

**Comment by alvarosabu** [comment]
Hey buddy @andretchen0 can you take a look to this one, I think I would prefer to tackle the test in the #631 task

**Pull request merged**
