### PR TITLE
fix: package exports

### PR DESCRIPTION
**Pull request by userquin**
Running `nr build && pnpm pack` checking the tar.gz file in https://arethetypeswrong.github.io/:

image

### CODE REVIEW

**Comment by userquin** [comment]
We can fix the package exports to be like this (remove CJS usage to promote `bundler`):

image

**Comment by userquin** [comment]
removing CJS...

**Comment by userquin** [comment]
image

**Comment by userquin** [comment]
You should remove rollup umd build...

**Review by alvarosabu — APPROVED** [review]
Thank you @userquin You da best!

**Pull request merged**
